### ISSUE TITLE
Wants credentials and doesn't accept them

### ISSUE THREAD

**Issue by DasJott** [zdohnal/system-config-printer#107]
I installed it on an Arch with Deepin-Desktop.

Before I can change or install anything, I am asked for username password.
Problem is, it is always declared wrong, but it's not. 

I always have to start this with sudo to work properly.

**Comment by zdohnal** [comment]
Hi,
the authentication is connected to CUPS, to be precise to its configuration in /etc/cups/cupsd.conf and /etc/cups/cups-files.conf. 
There is SystemGroup directive in cups-files.conf, which defines macro @SYSTEM , which is used in cupsd.conf in policies. So if you write username/password for user, which CUPS isn't configured to work with, the denial is correct. 
If you didn't set anything and got denial for user root (run the app as normal user and when the app asks for credentials, write credentials for root - you should get 'permission granted'), then it is the problem on s-c-p or CUPS side.

**Comment by DasJott** [comment]
Providing 'root' and according password it works.
I was just used to put my user credentials in there to make it work. Obviously that changed recently.
I found 'SystemGroup' in cups-files.conf and it was followed by 'sys root'.

**Comment by zdohnal** [comment]
If you didn't define your user or your group in SystemGroup in cups-files.conf or in 'Require user' in cupsd.conf, it is expected to not work. 
Maybe your distro had some different default setting for CUPS, but this is OS issue, not system-config-printer AFAIK.
Closing this issue, because it is not in system-config-printer - please probably open an issue/ask on OS support about it.
