### ISSUE TITLE
Partial translation of printer settings dialog box

### ISSUE THREAD

**Issue by LAfricain** [zdohnal/system-config-printer#79]
After installing a printer, often I have strings good translated (in French for me) but others don't.
I did this experience with hp:
![hp](https://user-images.githubusercontent.com/19690477/33482366-f90a900e-d698-11e7-90d8-2ebd07db3332.png)

With epson:
![epson](http://i66.tinypic.com/2m67o1u.jpg) 

and with other models. 
I looked in the po file, and I couldn't found the words not translated.
I searched a lot about this problem, how to translate this strings, but it seems that the ppd file is generated during installation. Currently I translate the ppd file just for me or my friends that don't understand english. But it can be interesting do it once and for all
If I can help for translation I would do it willingly.

**Comment by zdohnal** [comment]
Hi,
thank you for reporting this issue - would you mind telling me which strings aren't translated? I'm sorry I don't understand french.

**Comment by zdohnal** [comment]
Oh, I see - ok, that could be done in s-c-p.

**Comment by zdohnal** [comment]
Hmm, would you mind telling me which driver for which HP printer causes this issue? I think that can be even issue with ppd itself, not with system-config-printer @LAfricain

**Comment by LAfricain** [comment]
For the hp it is the HP LaserJet 1018 Foomatic/foo2zjs-z1 (recommended) but this problem is larger, because I meet it with multiple printers Canon, HP, Epson. Translation is quite variable, with some printers there is more translated text than others.
I discussed about this already on the french Ubuntu forum (I can found the post if you need), because users wanted to help for translation. For me it was difficult to understand were is really the issue...
If the issue is with the ppd how to perform it? But I think that strings as "Printing quality", Printing Density" or "Media type", are always in the printers windows, not just with my printer no?

What is strange for me, it is some are translate, others not... Because if I remember I looked in the sources for this word not translated, but I could find it.

Thanks for help :)

**Comment by LAfricain** [comment]
I change the title because this from @alainroger is better :)

**Comment by zdohnal** [comment]
@LAfricain I looked into HP LaserJet ppd file and there aren't any translations for other languages. If these string should be translated, it should be in ppd file like this (e.g. from hp laserjet 6p postscript ppd):

*fr.Translation PageSize/Format de page: ""

If such strings are missing in ppd, I'm sorry, s-c-p cannot do much about it. s-c-p calls 'ppdLocalize' CUPS function, which applies strings mentioned above (if available) in ppd. So if you find any ppd, which has such strings and isn't translated in s-c-p, please reopen this issue. I'll close this issue for now, because I think it is not s-c-p fault.

**Comment by LAfricain** [comment]
> So if you find any ppd, which has such strings and isn't translated in s-c-p, please reopen this issue

I can give you a lot of example, here you have one of an epson, and hp. Here a capture with a Canon with partial translation:
![canon-ir1133](https://user-images.githubusercontent.com/19690477/33569077-c8963aa8-d928-11e7-82c0-9a57ec05d1f6.png)

And a Samsung:
![samsung_m267x](https://user-images.githubusercontent.com/19690477/33569138-0989c7fa-d929-11e7-9db8-49fbf3f30971.png)


> I'll close this issue for now, because I think it is not s-c-p fault.

This is the question who is the "fault"? I search a lot about this. And what is strange it is that some strings are translated in s-c-p other not. For this reason I think there is a way to do it because the strings translated are not taken from the ppd but from the ".mo" s-c-p file.

I can reopen the issue, because I don't have the button :)

**Comment by zdohnal** [comment]
Ah, I think I know where problem lies - as I told before, translation comes from ppd file from strings like:

*fr.Translation PageSize/Format de page: ""

, but when such line is missing in ppd file, s-c-p tries to translate them by itself - it uses ppdippstr.py, *.po files and pot file.
The biggest and main downfall of s-c-p doing translation is I do not know which strings appear in all ppds which user can install (not mentioning its translation to different language than english) - that's why localization should be done in ppd file itself, not in application which use it.
So there are two ways now:
1) you create patch for english strings, which you found untranslated and translate them to french and create pull request - because I do not know which english strings you encountered and I do not understand french. (Or provide me english string and translated french string at least)
2) or report this issue on package, where ppd came from - foo2zjs, foomatic, hplip, gutenprint etc. - because IMHO it is more effective to fix it in ppd then in all apps which use it.

If you'll send me a patch or english strings and their french translation, I'll reopen this issue.

**Comment by LAfricain** [comment]
> you create patch for english strings, which you found untranslated and translate them to french and create pull request - because I do not know which english strings you encountered and I do not understand french. (Or provide me english string and translated french string at least)

Ok I can do this. I can find a certain number of lines that come back very frequently.
If I create the patch, I need to add the strings in the ppdippstr.py file? I have no idea how to do, but I'm motivating to do it... (I'll do some test, and give you a feedback for checks ok)

The problem with ppd files, it is if we wait the manufacturers... We will never have this strings translated. And If we do, step by step in s-c-p. We will translate it once for all and not in all ppd.

Thank you very much for help! You can reopen the bug.

**Comment by zdohnal** [comment]
IIRC, english sentences needs to be added to ppdippstr.py file to ppd object (after line 163) in same way as other strings are there - then I can call intltool-update (IIRC), which finds these strings and adds them to system-config-printer.pot file and to all .po files for all languages. Then we can add translation to correct .po files.
Problem with this solution is that strings will be translated only in s-c-p. If any other similar app exists, strings in there would be untranslated.

**Comment by LAfricain** [comment]
Ok I did some additions, I pulled request. See it and say me if it is ok.
I add strings 95 to 110 (because of the place in the gui)

**Comment by zdohnal** [comment]
'intltool-update -r' updated .pot and .po files. It even did some translations itself - would you mind checking them, adding missing french strings and correcting incorrect ones in current commit?

**Comment by LAfricain** [comment]
Ok I did some tests, it is ok the strings added appear in French great! (Just the title of the windows is now in English "Printers" and not "Imprimantes" and the icon name in the parameters windows) Now  I will continue to add the other strings. I have a suggestion, is it possible to use launchpad and rosetta for the translation? It is a very interesting tool to work on translation,  and we are more people...

**Comment by zdohnal** [comment]
Ok, thank you very much for the patch! But would you mind adding english strings in one go (in one patch)? Because I need to run 'intltool-update' again for these new strings and then ask you again to add translations for these strings now.
Translations of system-config-printer are on zanata https://fedora.zanata.org/iteration/view/system-config-printer/master/languages/it?dswid=4505

**Comment by LAfricain** [comment]
> But would you mind adding english strings in one go (in one patch)? 

Ok no problem!

**Comment by zdohnal** [comment]
Ok, .po files were regenerated again - would you mind checking+adding french translation?

**Comment by LAfricain** [comment]
I added still new strings! Now it will be done for a long time...
I will add and check new french po.

**Comment by zdohnal** [comment]
*.po files regenerated again - would you mind checking/adding french translation for these strings and #84 ?

**Comment by LAfricain** [comment]
Hello,
Now I'm waiting new regeneration of the po files. :) But for me this issue is closed.
